apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: my-node-app
        image: hypham3012/node-app
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer